name: Deploy ResumeFlow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: shreyiii/resumeflow-server:latest

      - name: Build and Push Client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: shreyiii/resumeflow-client:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/resumeflow
            docker compose pull
            docker compose up -d
            docker image prune -f